name: social_network_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_bloc: 8.1.5
  equatable: 2.0.5
  freezed_annotation: 2.4.1
  http: 1.1.0
  get_it: 7.6.7
  html: 0.15.4
  go_router: 13.0.1
  flutter_screenutil: 5.9.0
  flutter_secure_storage: 9.0.0
  getwidget: 4.0.0
  material_design_icons_flutter: 7.0.7296
  cupertino_icons: 1.0.8
  crypto: 3.0.1
  flutter_spinkit: 5.2.1
  connectivity_plus: 5.0.2
  easy_refresh: 3.3.4
  intl: 0.18.1
  image_picker: ^1.0.8
  photo_view: ^0.15.0
  socket_io_client: ^2.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: 2.4.7
  freezed: 2.4.5
  injectable_generator: 2.4.1
  json_serializable: 6.7.1

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/image_app/
    - assets/image_icon/
